routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Register route resource
Route::resource('categories', 'CategoriesController')->except([
    'index', 'show', 'destroy'
]);
Route::get('/categories/{categories}/destroy', 'CategoriesController@destroy')->name('categories.destroy');

Route::resource('products', 'ProductsController')->except([
    'index', 'show', 'destroy'
]);
Route::get('/products/{products}/destroy', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/sendmail', 'HomeController@sendmail')->name('user.sendmail');

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
        'name', 'price', 'category_id'
    ];

    /**
     * Get the category that owns the products.
     */
    public function category()
    {
        return $this->belongsTo(Categories::class);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use App\Http\Requests\ProductValidation;
use App\Http\Services\ProductsService;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;

class ProductsController extends Controller
{

    private $service = null;

    public function __construct(ProductsService $service)
    {
        $this->middleware('auth');
        $this->service = $service;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Categories::all(['id', 'name']);
        return view('features.products.form', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductValidation $request
     * @return Response
     */
    public function store(ProductValidation $request)
    {
        try {
            $products = $this->service->store($request->validated());
            Log::debug('created products: ' . $products);
            $request->session()->flash('message', 'Success create products');
        } catch (Exception $e) {
            Log::error('Error store products: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during storing data');
        }
        return redirect()->route('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $categories = Categories::all(['id', 'name']);
        $products = $this->service->find($id);
        Log::debug('edit products: ' . $products);
        return view('features.products.form', ['products' => $products, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductValidation $request
     * @param int $id
     * @return Response
     */
    public function update(ProductValidation $request, $id)
    {
        try {
            $products = $this->service->update($id, $request->validated());
            Log::debug('updated products: ' . $products);
            $request->session()->flash('message', 'Success update products');
        } catch (Exception $e) {
            Log::error('Error store products: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during update data');
        }
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            Log::debug('deleted products with id: ' . $id);
            $this->service->destroy($id);
            $request->session()->flash('message', 'Success delete products');
        } catch (Exception $e) {
            Log::error('Error store products: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during delete data');
        }
        return redirect()->route('home');
    }
}

resources/views/features/products/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Products Form</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST"
                              action="{{ \Illuminate\Support\Facades\Route::current()->named('products.create') ? route('products.store') : route('products.update', $products) }}">
                            @csrf
                            @if(\Illuminate\Support\Facades\Route::current()->named('products.edit'))
                                @method('PUT')
                            @endif

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ isset($products) ? $products->name : old('name') }}" required
                                           autocomplete="current-name">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="price"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                                <div class="col-md-6">
                                    <input id="price" type="text"
                                           class="form-control @error('price') is-invalid @enderror" name="price"
                                           value="{{ isset($products) ? $products->price : old('price') }}" required
                                           autocomplete="price">

                                    @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="categories_id"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Price') }}</label>

                                <div class="col-md-6">
                                    <select name="category_id" id="category_id"
                                            class="form-control @error('category_id') is-invalid @enderror" required>
                                        @foreach($categories as $c)
                                            <option value="{{ $c->id }}"
                                                    @if(isset($products) && $products->category_id == $c->id) selected @endif>{{ $c->name }}</option>
                                        @endforeach
                                    </select>

                                    @error('category_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/features/products/home.blade.php
<div class="card">
    <div class="card-header">
        <a href="{{route('products.create')}}" class="btn btn-outline-primary">Create</a>
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped mt-3">
            <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Category</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($products as $u)
                <tr>
                    <td>{{$u->name}}</td>
                    <td>{{$u->price}}</td>
                    <td>{{$u->category->name}}</td>
                    <td class="w-25">
                        <a href="{{route('products.edit', $u)}}" class="btn btn-outline-success">Edit</a>
                        <a href="{{route('products.destroy', $u)}}" class="btn btn-outline-danger">Remove</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>