routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Register route resource
Route::resource('categories', 'CategoriesController')->except([
    'index', 'show', 'destroy'
]);
Route::get('/categories/{categories}/destroy', 'CategoriesController@destroy')->name('categories.destroy');

Route::resource('products', 'ProductsController')->except([
    'index', 'show', 'destroy'
]);
Route::get('/products/{products}/destroy', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/sendmail', 'HomeController@sendmail')->name('user.sendmail');

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoriesValidation;
use App\Http\Services\CategoriesService;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;

class CategoriesController extends Controller
{

    private $service = null;

    public function __construct(CategoriesService $service)
    {
        $this->middleware('auth');
        $this->service = $service;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('features.categories.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(CategoriesValidation $request)
    {
        try {
            $categories = $this->service->store($request->validated()['name']);
            Log::debug('created categories: ' . $categories);
            $request->session()->flash('message', 'Success create categories');
        } catch (Exception $e) {
            Log::error('Error store categories: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during storing data');
        }
        return redirect()->route('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $categories = $this->service->find($id);
        Log::debug('edit categories: ' . $categories);
        return view('features.categories.form', ['categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(CategoriesValidation $request, $id)
    {
        try {
            $categories = $this->service->update($id, $request->validated());
            Log::debug('updated categories: ' . $categories);
            $request->session()->flash('message', 'Success update categories');
        } catch (Exception $e) {
            Log::error('Error store categories: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during update data');
        }
        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function destroy(Request $request, $id)
    {
        try {
            Log::debug('deleted categories with id: ' . $id);
            $this->service->destroy($id);
            $request->session()->flash('message', 'Success delete categories');
        } catch (Exception $e) {
            Log::error('Error store categories: ' . $e->getMessage());
            $request->session()->flash('message', 'Some error occurred during delete data');
        }
        return redirect()->route('home');
    }
}

resources/views/features/categories/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Categories Form</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form method="POST"
                              action="{{ \Illuminate\Support\Facades\Route::current()->named('categories.create') ? route('categories.store') : route('categories.update', $categories) }}">
                            @csrf
                            @if(\Illuminate\Support\Facades\Route::current()->named('categories.edit'))
                                @method('PUT')
                            @endif

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ isset($categories) ? $categories->name : old('name') }}" required
                                           autocomplete="current-name">

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Submit') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/features/categories/home.blade.php
<div class="card">
    <div class="card-header">
        <a href="{{route('categories.create')}}" class="btn btn-outline-primary">Create</a>
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped mt-3">
            <thead>
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $u)
                <tr>
                    <td>{{$u->name}}</td>
                    <td class="w-25">
                        <a href="{{route('categories.edit', $u)}}" class="btn btn-outline-success">Edit</a>
                        <a href="{{route('categories.destroy', $u)}}" class="btn btn-outline-danger">Remove</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>